networks:
  my-net:
    name: my-net
    external: true
services:
  nckh-user:
    image: toan3082004/nckh-user-service:latest
    ports:
      - 50051
    networks:
        - my-net
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=nckh.hareta.online
      - VIRTUAL_HOST=nckh.hareta.online
      - VIRTUAL_PATH=/v1/user/
      - PORT=50051
  nckh:
    image: toan3082004/nckh:latest
    ports:
      - 3000
    networks:
      - my-net
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=nckh.hareta.online
      - VIRTUAL_HOST=nckh.hareta.online
      - VIRTUAL_PATH=/
      - USER_CLIENT_URL=nckh-be-nckh-user-1:50051
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
